
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

format = '''
[╭──](fg:arrow)$hostname$sudo$username$directory$git_branch
[╰────](fg:arrow)$character
'''

right_format = "${custom.sh_version}${custom.kern_version}$cmd_duration"

palette = "n7-like"

[palettes.n7-like]
bg = "#161F27"
os_fg = "#B37BA4"
user_fg = "#17B890"
dir_fg = "#62D6F9"
kern_fg = "#B37BA4"
sh_fg = "#17B890"
duration_fg = "#B37BA4"
git_branch_fg = "#62D6F9"
arrow_error_fg = "#B10F2E"
arrow_fg = "#FEEFDD  "

[line_break]
disabled = false

[hostname]
ssh_only = false
style = 'bg'
format = ' []($style)[ $hostname](bg:$style fg:os_fg)[]($style) '
trim_at = '.companyname.com'
disabled = false

[username]
style_user = 'bg'
format = '[]($style)[ $user](bg:$style fg:user_fg)[]($style)'
disabled = false
show_always = true

[character]
success_symbol = "[](fg:arrow_fg)"
error_symbol = "[](fg:arrow_error_fg)"

[directory]
style = "bg"
read_only_style = "bg"
before_repo_root_style = "bg"
format = ' []($style)[ $path](bg:$style fg:dir_fg)[$read_only]($read_only_style)[]($style)'
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = true
read_only = " 󰌾 "

[git_branch]
style = 'bg'
format = ' []($style)[ $branch $remote_name](bg:$style fg:git_branch_fg)[]($style)'
disabled = false
always_show_remote = true
only_attached = true

[cmd_duration]
style = 'bg'
format = ' []($style)[ $duration](bg:$style fg:duration_fg)[]($style)'
show_milliseconds = true
min_time = 5

[sudo]
style = 'bg'
format = '[]($style)[󰥿 superuser](bg:$style fg:duration_fg)[]($style) '
disabled = false

[custom.sh_version]
disabled = false
when = "true"
command = "zsh 2>/dev/null --version | head -n 1 | awk '{print $2 $3}'"
style = 'bg'
format = ' []($style)[󰞷 zsh via $output](bg:$style fg:sh_fg)[]($style)'

[custom.kern_version]
disabled = false
when = "true"
command = "uname -r 2>/dev/null"
style = 'bg'
format = ' []($style)[ $output](bg:$style fg:kern_fg)[]($style)'
